lint pass
EvenTITO/eventito-frontend pull request #136
Opened 2024-10-08 02:17 UTC by lucasveron

2024-10-08 03:05 UTC, FernandoSinisi requested changes

2024-10-08 03:05 UTC, FernandoSinisi commented on src/pages/(events-manage)/events/[id]/roles/chair/index.jsx
> +  const myChairData = isOrganizer
si es organizer el "myChairData" es un evento, no es confuso ?

no queda mas simple algo como:
```
const isOrganizer = eventData?.roles && eventData?.roles.includes(ORGANIZER_ROLE)
let tracksSettled = []
if(organizer):
    tracksSettled = eventData?.tracks || []
else:
    const myChairData =  useGetMyChair()
    tracksSettled  = myChairData.data?.tracks || []
```

2024-10-08 03:05 UTC, FernandoSinisi commented on src/index.css
> +    --muted-foreground: 215 20.2% 65.1%;
WTF, esto es por el update del linter del packege.json no ??

2024-10-09 00:50 UTC, lucasveron commented on src/index.css
> +    --muted-foreground: 215 20.2% 65.1%;
sip

2024-10-09 00:50 UTC, lucasveron commented on src/pages/(events-manage)/events/[id]/roles/chair/index.jsx
> +    : useGetMyChair()
lo probe en donde ocurre el error y fue bien

2024-10-09 00:51 UTC, lucasveron commented on src/pages/(events-manage)/events/[id]/roles/chair/index.jsx
> +    error: eventError,
Se agrega, aca para usarse luego

2024-10-11 01:46 UTC, closed without merging